language: java
addons:
  sonarcloud:
    organization: "blackmania"
    token: "344f22b5fe3f9b02a637246075d5167467b37448"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=BlackMania_DrawTogetherApi
