language: java
addons:
  sonarcloud:
    organization: "blackmania"
    token:
      secure: "L+FIZQn/Vd0u66bKiVq8HunGP3r+BxmbUqF+X4Spq+PrPFxzeyqD71nX0v2nnWttyfZkHbZ1lg16DCVuAEqegRfoVz0Q0qq68jircLuXjXMNhBervgJqh639iaTApCZLmD5/A4xw4zTeK47KPC9snrg4ev4rit532rpKOJaEguow25HZ/vb0WKg9K48R7kOqyO2OYmiZGKEsA3NfKg76h3fZGAuko6TNBHU5GsH+UExhgoxpmDpFGjFunN8MO0u3Pvt2GpteeUksgV6ivjBMV0Al63y2BmID4f1KLv7czTARH50TayE4COC6kOETYe7JQ3mGgOKpFL6APmz6Hd9Dc/TYszoJdDCfPqEWrBAriYyRhIZcNapgtEh2cv6Yxr7IRPCBumisZwuPId7PqI21ufQ2WIBStLzQThH0p3UorOGO9BaVyMA2RK6VAcTiv4TTZDsc2p2Tj8eL2TOS1LgEZUTY2ESgFu5TnVM90iViXIUkFm37P7W3pKlofMmCMJXWogpu8R1SV6rt5rKdyw0rhbn9D6WrPlykyaKfPYjvJmFBji8/iNqvUkx+zkhvz5r1c+Ik3CJs1NfWr9T8QOJYNBBXAWAzG15h6i7Kn+/gC4O6VtWuRhGXXLcgWRw3ffaa3+iox4gHei7VmMGVE0fwdBB8wnGjChuQXQyEgCqpzxA="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=BlackMania_DrawTogetherApi
